### ISSUE TITLE
Arrays in Python

### ISSUE THREAD

**Issue by uvainio** [tschoonj/xraylib#87]
Hi Tom (and others),

do you think it would be a big task to change the Python implementation such that the functions would take in energy also as an array (e.g. numpy), such that one does not need to for loop always the calls to xraylib over many input energies? I think it would give a great speed increase.

Kind regards,

Ulla

**Comment by uvainio** [comment]
Hi Tom,

thanks a lot! I was totally unaware of this xraylib_np. However, it seems it is missing some functions like the compound ones (e.g. CS_Total_Kissel_CP). And ideally the same function would take ints and numpy arrays both, so one would not need to switch between libraries and make variables numpy arrays. Would this be something where I could easily help if I somehow could reconstruct the xraylib-code such that it would also consider numpy arrays (mostly just in the energy!)?

Cheers,

Ulla

**Comment by tschoonj** [comment]
Hey Ulla,

When I wrote these bindings I explicitly left out all functions that had strings as arguments as I did not know what to do with them in Cython. 

I recently learned a few new Cython tricks and I think that I should get that working now, after a couple of changes.

I am not entirely happy with the `xraylib_np` implementation for a number of reasons, including the fact that it enforces the arguments to be numpy arrays instead of allowing also simple scalars. 

A rewrite is indeed in order, but as writing these bindings is very tedious it is probably best to have the Cython code generated with a python script.

I would be more than happy if you could help out here: let me know if you need any help and I will gladly help out!

Best,

Tom

**Comment by tschoonj** [comment]
Hi Ulla,

I will be closing this for now.

Best,

Tom
